name: Build, test and publish
on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      generate-build-number: false
      conventional-commits-publish-conditions: false
      workloads: maui
      install-tizen: true
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}