name: Build and test
on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build abd test
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      dotnet-version: 8.0.x
      project-path: src/libs/LangChain.Providers.Maui/LangChain.Providers.Maui.csproj
      additional-command: dotnet build samples/LangChain.Samples.Maui/LangChain.Samples.Maui.csproj --framework net8.0-windows10.0.19041.0 --configuration Release --nologo
      run-tests: false
      os: windows-latest
      generate-build-number: false
      conventional-commits-publish-conditions: false
      workloads: maui
      install-tizen: true
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'
